export const THEME = {
    colors: {
        primary: '#0B6623',
        primaryLight: '#E8F5E9',
        primaryDark: '#053E14',
        accent: '#D4AF37',
        accentLight: '#FCF8E3',
        textDark: '#1A252C',
        textMuted: '#64748B',
        bgLight: '#F8FAFC',
        bgCard: '#FFFFFF',
        border: '#E2E8F0',
        urgencyHigh: '#EF4444',
        urgencyMedium: '#F59E0B',
        urgencyLow: '#3B82F6',
        success: '#10B981',
        info: '#0EA5E9',
        white: '#FFFFFF',
    },
    shadows: {
        premium: {
            shadowColor: '#000',
            shadowOffset: { width: 0, height: 4 },
            shadowOpacity: 0.08,
            shadowRadius: 12,
            elevation: 3,
        },
        float: {
            shadowColor: '#0B6623',
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.15,
            shadowRadius: 16,
            elevation: 6,
        },
    },
    fonts: {
        regular: '400',
        medium: '500',
        bold: '700',
        black: '900',
    },
    radius: {
        sm: 8,
        md: 12,
        lg: 16,
        xl: 24,
        pill: 50,
    },
    spacing: {
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        xxl: 24,
    },
};